run:
  tests: false

severity:
  default-severity: error
  rules:
    - severity: warning
      linters:
      - errcheck # for now, make errcheck only a warning, TODO: remove it later
      - deadcode
